apiVersion: apps/v1
kind: Deployment

metadata:
  name: event-service-green

spec:
  replicas: 1

  selector:
    matchLabels:
      app: event-service
      version: green

  template:
    metadata:
      labels:
        app: event-service
        version: green

    spec:
      containers:
      - name: event-service

        image: event-service:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 8000

        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY

        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_DEFAULT_REGION
